package com.amal.amalproject.utils.enums;

public enum AccountStatus {
    STATUS_ACTIVE_NOT_VERIFIED_PHONE_NOT_VERIFIED_MAIL,
    STATUS_ACTIVE_VERIFIED_PHONE_NOT_VERIFIED_MAIL,
    STATUS_ACTIVE_NOT_VERIFIED_PHONE_VERIFIED_MAIL,
    STATUS_ACTIVE_VERIFIED_PHONE_VERIFIED_MAIL,
    STATUS_DEACTIVATE,
    STATUS_BANNED
}
